### ISSUE TITLE
Worried about Copper farm

### ISSUE THREAD

**Issue by frisno-b** [n1n3t34m/UnpersistMobs#1]
I name tag every mob I like to keep, except the zombies/drowned in the reinforcement copper farm I have in the end.
Is there a setting to exempt the end dimension?

**Comment by dentatar** [comment]
No, at least for now :) And i didn't actually test reinforcement-based farms… Will look into it and think about possible solutions, thanks

**Comment by frisno-b** [comment]
Thank you, i keep it in logOnly mode for now.
Is there a way to let the plugin write the log in chat ? so anyone loading in a persistent mod can hunt them down if they want to.

**Comment by dentatar** [comment]
I get your worrying, if you leave for longer than `ticksLived` you would need to bring new zombies to restart the farm. And nametags are not really feasible since mobs are renewed constantly. I can't really see a way to distinguish mobs in such farms to automatically exclude them, so ye… I will add an option to exclude certain worlds. For now you can add `REINFORCEMENTS` to list of ignored reasons tho :)

As for logging into chat, this may actually be a good idea! Alert only closest players (or else it would be really spammy) and maybe drop more XP to encourage hunting? I will consider that in the future…

**Comment by dentatar** [comment]
Done and released on Modrinth: https://modrinth.com/plugin/unpersistmobs/version/1.4-SNAPSHOT
